
if (TARGET doctest::doctest)
  include(doctest)
  function(doctest_add_test target)
    add_executable(${target} ${ARGN})
    target_link_libraries(${target} PRIVATE doctest::doctest_with_main)
    doctest_discover_tests(${target} ADD_LABELS ${REFLEX_TEST_GROUP})

    if (REFLEX_TEST_GROUP)
      if (NOT TARGET ${REFLEX_TEST_GROUP}-tests)
         add_custom_target(${REFLEX_TEST_GROUP}-tests)
      endif()
      add_dependencies(${REFLEX_TEST_GROUP}-tests ${target})
    endif()

  endfunction()
else()
  message(WARNING "Doctest not available")
  function(doctest_add_test target)
    message(WARNING "${target} not available (Doctest missing)")
  endfunction()
endif()